package com.y271727uy.moderndelight.util;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.ModLoadingContext;

public final class ModConfig {
    public static final ForgeConfigSpec SPEC;
    
    // Biogas System
    public static final ForgeConfigSpec.ConfigValue<String> DIGESTATE;
    public static final ForgeConfigSpec.BooleanValue ALLOW_GAS_CANISTER_EXPLODE;
    public static final ForgeConfigSpec.BooleanValue ALLOW_GAS_CANISTER_IN_NETHER;
    public static final ForgeConfigSpec.IntValue GAS_CANISTER_VOLUME;
    
    // Power System
    public static final ForgeConfigSpec.IntValue ACDC_CONVERTER_MAX_WORK_SPEED;
    public static final ForgeConfigSpec.IntValue ENERGY_GENERATED_BY_FARADAY_GENERATOR;
    public static final ForgeConfigSpec.DoubleValue PHOTOVOLTAIC_GENERATOR_MULTIPLIER;
    public static final ForgeConfigSpec.DoubleValue WIND_TURBINE_MULTIPLIER;
    public static final ForgeConfigSpec.DoubleValue TESLA_COIL_CONVERSION_EFFICIENCY;
    public static final ForgeConfigSpec.DoubleValue CHARGING_POST_EFFICIENCY;
    
    // Seasoning
    public static final ForgeConfigSpec.IntValue MAX_SEASONINGS;
    
    static {
        ForgeConfigSpec.Builder builder = new ForgeConfigSpec.Builder();
        
        builder.push("biogas_system");
        
        DIGESTATE = builder.comment("Item used as digestate")
                .define("digestate", "minecraft:bone_meal");
        
        ALLOW_GAS_CANISTER_EXPLODE = builder.comment("Allow gas canister to explode")
                .define("allowGasCanisterExplode", true);
        
        ALLOW_GAS_CANISTER_IN_NETHER = builder.comment("Allow gas canister in Nether")
                .define("allowGasCanisterInNether", false);
        
        GAS_CANISTER_VOLUME = builder.comment("Gas canister volume in mB")
                .defineInRange("gasCanisterVolume", 6000, 100, 30000);
        
        builder.pop();
        builder.push("power_system");
        
        ACDC_CONVERTER_MAX_WORK_SPEED = builder.comment("ACDC Converter max work speed")
                .defineInRange("acdcConverterMaxWorkSpeed", 20, 1, 50);
        
        ENERGY_GENERATED_BY_FARADAY_GENERATOR = builder.comment("Energy generated by Faraday Generator (FE/s)")
                .defineInRange("energyGeneratedByFaradayGenerator", 200, 10, 1000);
        
        PHOTOVOLTAIC_GENERATOR_MULTIPLIER = builder.comment("Photovoltaic Generator multiplier")
                .defineInRange("photovoltaicGeneratorMultiplier", 2.0, 0.05, 10.0);
        
        WIND_TURBINE_MULTIPLIER = builder.comment("Wind Turbine multiplier")
                .defineInRange("windTurbineMultiplier", 2.0, 0.05, 10.0);
        
        TESLA_COIL_CONVERSION_EFFICIENCY = builder.comment("Tesla Coil conversion efficiency")
                .defineInRange("teslaCoilConversionEfficiency", 0.8, 0.005, 1.0);
        
        CHARGING_POST_EFFICIENCY = builder.comment("Charging Post efficiency")
                .defineInRange("chargingPostEfficiency", 0.9, 0.005, 1.0);
        
        builder.pop();
        builder.push("seasoning");
        
        MAX_SEASONINGS = builder.comment("Maximum number of seasonings")
                .defineInRange("maxSeasonings", 5, 1, 15);
        
        builder.pop();
        
        SPEC = builder.build();
    }
    
    // Helper methods for backward compatibility
    public static String getDigestate() {
        return DIGESTATE.get();
    }
    
    public static int getAcDcConverterMaxWorkSpeed() {
        return ACDC_CONVERTER_MAX_WORK_SPEED.get();
    }
    
    public static int getEnergyGeneratedByFaradayGenerator() {
        return ENERGY_GENERATED_BY_FARADAY_GENERATOR.get();
    }
    
    public static double getPhotovoltaicGeneratorMultiplier() {
        return PHOTOVOLTAIC_GENERATOR_MULTIPLIER.get();
    }
    
    public static double getWindTurbineMultiplier() {
        return WIND_TURBINE_MULTIPLIER.get();
    }
    
    public static double getTeslaCoilConversionEfficiency() {
        return TESLA_COIL_CONVERSION_EFFICIENCY.get();
    }
    
    public static double getChargingPostEfficiency() {
        return CHARGING_POST_EFFICIENCY.get();
    }
    
    public static boolean isAllowGasCanisterExplode() {
        return ALLOW_GAS_CANISTER_EXPLODE.get();
    }
    
    public static boolean isAllowGasCanisterInNether() {
        return ALLOW_GAS_CANISTER_IN_NETHER.get();
    }
    
    public static int getGasCanisterVolume() {
        return GAS_CANISTER_VOLUME.get();
    }
    
    public static int getMaxSeasonings() {
        return MAX_SEASONINGS.get();
    }
    
    public static void register() {
        ModLoadingContext.get().registerConfig(net.minecraftforge.fml.config.ModConfig.Type.COMMON, SPEC, "moderndelight-config.toml");
    }
}
